version: '3.7'

services:
  players:
    image: players:latest
    container_name: players
    build:
      context: .
      dockerfile: docker/players.DockerFile
    restart: unless-stopped
    networks:
      - net-internal
    ports:
      - '18080:8080'
    environment:
      HOST: :8080

  auth_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - '5433:5432'
    networks:
      - net-internal
    volumes:
      - auth_db:/var/lib/postgresql/data

  integration:
    image: integration:latest
    container_name: integration
    build:
      context: .
      dockerfile: docker/integration.DockerFile
    restart: unless-stopped
    networks:
      - net-internal
    ports:
      - '18081:8081'
    environment:
      HOST: :8081
      PLAYERS_HOST: players:8080
      DATABASE_DSN: postgres://postgres:postgres@auth_db:5432/auth_db?sslmode=disable
      JWT_KEY: NJFKDNB34njk3hrjk
      HASH_KEY: hdsjhgfjkHJJKHBKEdshd%^&%322

    depends_on:
      - players
      - auth_db

networks:
  net-internal:
    driver: bridge

volumes:
  auth_db: