.PHONY:

swag_players:
	swag init -g cmd/players/main.go -o cmd/players/docs

docker_down:
	docker-compose stop
	docker-compose down
	docker rmi players

docker_up:
	docker-compose up

containers:
	docker ps -a
