.PHONY:

swag_players:
	swag init -g cmd/players/main.go -o cmd/players/docs

docker_down:
	docker-compose stop
	docker-compose down
	docker rmi players integration

docker_up:
	docker-compose up

containers:
	docker ps -a

proto:
	protoc --proto_path=./pb/integration/ \
		--go_out=./pb/integration \
		--go_opt=paths=source_relative \
		--go-grpc_out=./pb/integration \
		--go-grpc_opt=paths=source_relative \
		./pb/integration/integration.proto

	protoc --proto_path=./pb/auth/ \
    		--go_out=./pb/auth \
    		--go_opt=paths=source_relative \
    		--go-grpc_out=./pb/auth \
    		--go-grpc_opt=paths=source_relative \
    		./pb/auth/auth.proto